config/routes.rb
Rails.application.routes.draw do

	
  get 'home/index'

	get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'


   devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :categories
  
  resources :sales do
    resources :assets, only: [:create]
  end
  root 'sales#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
	  mount_uploader :file_upload, FileUploader

	  has_many :assets
	  belongs_to :user
	  belongs_to :category

	  geocoded_by :address_map
        after_validation :geocode
    
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
   def index
     @sales =Sale.where(user_id: current_user)
      @hash = Gmaps4rails.build_markers(@sales) do |sale, marker|
        marker.lat sale.latitude
        marker.lng sale.longitude
        marker.infowindow sale.description
     end
    @message = Message.new
    @sales = Sale.all
  # @sales = Sale.where(user_id: current_user)
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sales = Sale.where(user_id: current_user)
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:title, :description, :date, :address_map, :latitude, :longitude, :category_id, :user_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_assets.html.erb
<h3>Assets for the sale</h3>

<ul>
  <%- @sale.assets.each do |asset| %>
    <li>
      <%= link_to asset.file_url do %>
        <%= image_tag asset.file_url(:thumb), width: 120 if asset.file_url =~ /(gif|jpg|jpeg|png|bmp)$/ %>
        <%= asset.file_identifier %>
      <%- end %>
    </li>
  <% end %>
</ul>

<%= form_for [ @sale, @sale.assets.build ], multipart: true do |f| %>
<p>
  <%= f.file_field :file %>
  <%= f.submit %>
</p>
<% end %>

app/views/sales/_form.html.erb
<div class="container">
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<center><div class="brand-before"> </center>
  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :sale_title %>
  </div>
  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description, id: :sale_description %>
  </div>
   <div class="field">
    <%= form.label :category_id %><br>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>
   <div class="field">
     <%= form.label :user_id %><br>
     <%= form.hidden_field :user_id,value: current_user.id%>
  </div>

  <div class="field">
    <%= form.label :date %><br>
    <%= form.date_select :date, id: :sale_date %>
  </div>

  <div class="field">
    <%= form.label :address_map %><br>
    <%= form.text_field :address_map, id: :sale_address_map %>
  </div>

  <div class="field">
    <%= form.label :latitude %><br>
    <%= form.text_field :latitude, id: :sale_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %><br>
    <%= form.text_field :longitude, id: :sale_longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>
</div>
</div>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<br><br>
 <header class="intro-header" style="background-image: url('/assets/img/home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>E-Sale</h1>
                        <hr class="small">
                        <!-- <span class="subheading">A Clean Blog Theme by Start Bootstrap</span> -->
                    </div>
                </div>
            </div>
        </div>
    </header>
<center><h1>Sales</h1></center>
     <br>
<table class="table table-striped table table-bordered table table-hover" >
  <thead>
    <tr class="success">
    <th>Category</th>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Address map</th>
     <!--  <th>Action</th> -->

     <!--  <th>Latitude</th>
      <th>Longitude</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
       <td><%= sale.category && sale.category.name %></td>
        <td><%= sale.title %></td>
        <td><%= sale.description %></td>
        <td><%= sale.date %></td>
        <td><%= sale.address_map %></td>
      <!--   <td><%= sale.latitude %></td>
        <td><%= sale.longitude %></td> --> 
        <td><%= link_to 'Show', sale %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<script src="https://maps.googleapis.com/maps/api/js?libraries= AIzaSyCctXxRoyd4eIHR6krFCb7fJOFEV_K_0eU "></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBh0xK-DJhS5dbGJR5gRbm4192uYzJYIzI"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> 
<center><div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div></center>
<script type="text/javascript">
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){

        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();

      });


</script>   

    <!-- 
        <%= link_to  new_sale_path %> -->

app/views/sales/new.html.erb
<center><h1>New Sale</h1></center>
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= render 'form', sale: @sale %>
     </div>

app/views/sales/show.html.erb
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<center><div class="container"> </center>

<p id="notice"><%= notice %></p>

<p>
    <strong>Category:</strong>
    <%= @sale.category.name %>
  </p>


<p>
  <strong>Title:</strong>
  <%= @sale.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sale.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sale.date %>
</p>

<p>
  <strong>Address map:</strong>
  <%= @sale.address_map %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sale.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sale.longitude %>
</p>
<br><br>
<center><%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@sale.latitude}%2C#{@sale.longitude}" %></center> 


<%= render "assets" %>
<%= link_to 'Edit', edit_sale_path(@sale), class: "btn btn-info" %> 
<%= link_to 'Back', sales_path, class: "btn btn-primary" %>
<%= link_to 'New Sale', new_sale_path, class: "btn btn-success" %>
</div>
</div>