config/routes.rb
Rails.application.routes.draw do

	
  get 'home/index'

	get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'


   devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :categories
  
  resources :sales do
    resources :assets, only: [:create]
  end
  root 'sales#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
	belongs_to :sale
   mount_uploader :file, FileUploader
end

app/models/category.rb
class Category < ApplicationRecord
	has_many  :sales
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true

end

app/models/sale.rb
class Sale < ApplicationRecord
	  mount_uploader :file_upload, FileUploader

	  has_many :assets
	  belongs_to :user
	  belongs_to :category

	  geocoded_by :address_map
        after_validation :geocode
    
end

app/models/user.rb
class User < ApplicationRecord
	has_many :sales
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index] 

  protect_from_forgery with: :exception
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

  def create
    @sale = Sale.find params[:sale_id]
    @asset = @sale.assets.build asset_params

    if @asset.save
      redirect_to @sale, notice: "File was successfully uploaded."
    else
      redirect_to @sale, alert: "File was not uploaded."
    end
  end



  def asset_params
    params.require(:asset).permit(:file)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@sales = Sale.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if @message.valid?
      MessageMailer.new_message(@message).deliver
      redirect_to contact_path, notice: "Your messages has been sent."
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end

private

  def message_params
    params.require(:message).permit(:name, :email,  :content)
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
   def index
     @sales =Sale.where(user_id: current_user)
      @hash = Gmaps4rails.build_markers(@sales) do |sale, marker|
        marker.lat sale.latitude
        marker.lng sale.longitude
        marker.infowindow sale.description
     end
    @message = Message.new
    @sales = Sale.all
  # @sales = Sale.where(user_id: current_user)
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sales = Sale.where(user_id: current_user)
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:title, :description, :date, :address_map, :latitude, :longitude, :category_id, :user_id)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/_footer.html.erb
<!-- footer top start -->
			<!-- ================ -->
			
		<br><br>	
			<!-- footer start (Add "dark" class to #footer in order to enable dark footer) -->
			<!-- ================ -->
			<footer id="footer1" class="clearfix dark">

				<!-- .footer start -->
				<!-- ================ -->
				<div class="footer1">
					<div class="container">
						<div class="footer-inner">
							<div class="row">
								<div class="col-md-6 col-md-offset-3">
									<div class="footer-content text-center padding-ver-clear">
									
										<ul class="list-inline mb-20">
											<li><i class="text-default fa fa-map-marker pr-5"></i>2950 W Arthur Ave,Chicago,IL,60645</li>
											<li><a  class="link-dark"><i class="text-default fa fa-phone pl-10 pr-5"></i>312-981-9464</a></li>
											<li><a  class="link-dark"><i class="text-default fa fa-envelope-o pl-10 pr-5"></i>fidansaid@gmail.com</a></li>
										</ul>
									
										<div class="separator"></div>
										<p class="text-center margin-clear">Copyright © 2017 The Project by <a target="_blank" >Esale</a>. All Rights Reserved</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- .footer end -->

        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    
                </div>
            </div>
        </div>
    </footer>
			<!-- footer end -->
        <!-- End Promo Section -->
        

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse bg-primary">
    <ul class="nav navbar-nav">
      <a  class="navbar-brand" href="#"><div class="name1" >Esale </div></a>
      <ul class="nav navbar-nav navbar-right">
                      
        <li><a href=<%=    home_index_path  %>><span class="glyphicon glyphicon-home"></span>Home</a></li>

      <li><a href=<%=   new_sale_path  %>><span class="glyphicon glyphicon-list-alt"></span>Sales</a></li>

     <li><a href=<%= root_path   %>><span class="glyphicon glyphicon-list"></span>Blog</a></li>

       <li><a href=<%= root_path  %>><span class="glyphicon glyphicon-list"></span>Post</a></li>

       <li><a href=<%= contact_path  %> ><span class="glyphicon glyphicon-phone"></span>Contact Us</a></li>

      <!-- <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
       <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li>
      <li><a class="dec" href="#"></a></li> -->
    </ul> 
  
  
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><a href="<%= edit_user_registration_path %>"> <span class="glyphicon glyphicon-user"></span> Edit profile</a></li>
        <li><a href="<%= destroy_user_session_path %>" data-method="delete"> <span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      <%else%>
        <li><a href=<%= new_user_registration_path  %>><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href=<%=new_user_session_path %> ><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <%end%>
    </ul>
  </div>
</nav>
      <!--========== devies   ==========-->        
  </div>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Esale</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/nav" %>
  <br>
  <!-- Collect the nav links, forms, and other content for toggling -->
             <body style="height:1500px">
<% if notice.present? %>
        <div class="alert alert-info" id="flash_message" style="text-align: center">
          <button class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
        <%= notice %>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="alert alert-danger" id="flash_message" style="text-align: center; background-color:#ff0042;color:white">
          <button class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
          <%= alert %>
        </div>
      <% end %>

<div class="container">
    <%= yield %>
    <%= render "layouts/footer" %>
</div>    
  </body>
</html>